services:
  postgres:
    image: postgres:16
    container_name: student_library_db
    restart: always
    environment:
      POSTGRES_DB: student_library
      POSTGRES_USER: student_user
      POSTGRES_PASSWORD: password
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student_user -d student_library"]
      interval: 10s
      retries: 5
      timeout: 5s

  grafana:
    image: grafana/grafana:10.4.0
    container_name: student_grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Europe/Moscow
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  client:
    build: ./client
    ports:
      - "3001:3001"  
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    build: ./server
    container_name: student_library_server
    restart: always
    environment:
      - POSTGRES_DB=student_library
      - POSTGRES_USER=student_user
      - POSTGRES_PASSWORD=password
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:


